apiVersion: v1
kind: Service  
metadata:
  name: envoy
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    #nodePort: 30080
  - name: https
    port: 443 
    targetPort: 443
    #nodePort: 30443
  - name: admin
    port: 9901
    targetPort: 9901
    #nodePort: 30901
  selector:
    app: envoy